# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 10:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=10)),
                ('aadhar_number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_gaurdian', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_packets_available', models.IntegerField()),
                ('first_aid_packets_available', models.IntegerField()),
                ('bedding_packets_available', models.IntegerField()),
                ('water_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('number_of_members', models.IntegerField()),
                ('family_address_line_1', models.CharField(max_length=100)),
                ('family_address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('family_address_line_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity_of_people', models.IntegerField()),
                ('capacity_used', models.IntegerField()),
                ('food_packets_needed', models.IntegerField()),
                ('first_aid_packets_needed', models.IntegerField()),
                ('shelter_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shelter_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shelter_type', models.CharField(choices=[('g', 'government'), ('a', 'ad-hoc')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_supplied', models.IntegerField()),
                ('supply_type', models.CharField(choices=[('fp', 'food_packet'), ('fa', 'first_aid'), ('b', 'beddings'), ('w', 'water')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, choices=[('a', 'Admin'), ('o', 'Operator'), ('s', 'Supplier')], max_length=10, null=True)),
                ('civilian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Shelter')),
            ],
        ),
        migrations.AddField(
            model_name='supplierlogs',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SystemUsers'),
        ),
        migrations.AddField(
            model_name='currentstock',
            name='current_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shelter'),
        ),
        migrations.AddField(
            model_name='civilians',
            name='allocated_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_shelter', to='app.Shelter'),
        ),
        migrations.AddField(
            model_name='civilians',
            name='current_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_shelter', to='app.Shelter'),
        ),
        migrations.AddField(
            model_name='civilians',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Families'),
        ),
        migrations.AddField(
            model_name='civilians',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='civilians',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
