# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180329_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksdata',
            name='in_disaster',
            field=models.BooleanField(default=False),
        ),
    ]
