# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180316_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='aadhar_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='systemusers',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
