# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blocksdata_in_disaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
