# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shelter_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationtofamilies',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Shelter'),
            preserve_default=False,
        ),
    ]
